on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v1.7
        with:
          src_dir: src
          dest_dir: my-theme
          portal_id: ${{ env.HUBSPOT_PORTAL_ID || secrets.hubspot_portal_id }}
          personal_access_key: ${{ env.HUBSPOT_PERSONAL_ACCESS_KEY || secrets.hubspot_personal_access_key }}
